# packaging/rpm/Containerfile.build
#
# Fedora 43 build container for Conary RPMs.
# Includes Rust toolchain and all build dependencies.

FROM registry.fedoraproject.org/fedora:43

RUN dnf install -y \
        rust \
        cargo \
        rpm-build \
        openssl-devel \
        xz-devel \
        pkg-config \
        gcc \
        cmake \
        perl \
    && dnf clean all

RUN mkdir -p /rpmbuild/{BUILD,RPMS,SRPMS,SOURCES,SPECS} /output

WORKDIR /rpmbuild
