#!/usr/bin/env bash
# scripts/sync-brand.sh
#
# Materializes shared/brand/ into site/ and web/.
#
#   sync-brand.sh            write the generated files (default)
#   sync-brand.sh --check    verify the trees match the owner, write nothing
#
# Both frontends run this as predev/precheck/prebuild, so a contributor never
# has to invoke it directly. Generated paths are gitignored; shared/brand/ is
# the only tracked copy.
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(dirname "$script_dir")"
owner="$repo_root/shared/brand"
apps=(site web)

mode="sync"
case "${1:-}" in
    --check) mode="check" ;;
    "") ;;
    *)
        echo "usage: $(basename "$0") [--check]" >&2
        exit 2
        ;;
esac

[[ -f "$owner/tokens.css" ]] || {
    echo "ERROR: missing brand owner: shared/brand/tokens.css" >&2
    exit 1
}

drift=0

# Writes $2 from $1 in sync mode; in check mode reports any difference instead.
materialize() {
    local src="$1" dst="$2" label="$3"

    if [[ "$mode" == "check" ]]; then
        if [[ ! -e "$dst" ]]; then
            echo "DRIFT: missing generated file: $label" >&2
            drift=1
        elif ! cmp -s "$src" "$dst"; then
            echo "DRIFT: $label does not match shared/brand (edit the owner, not the copy)" >&2
            drift=1
        fi
        return
    fi

    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
}

generated_css="$(mktemp)"
trap 'rm -f "$generated_css"' EXIT
{
    echo "/* GENERATED by scripts/sync-brand.sh from shared/brand/tokens.css. */"
    echo "/* Do not edit this file. Edit the owner and rebuild. */"
    cat "$owner/tokens.css"
} > "$generated_css"

for app in "${apps[@]}"; do
    app_dir="$repo_root/$app"
    [[ -d "$app_dir" ]] || {
        echo "ERROR: unknown frontend directory: $app" >&2
        exit 1
    }

    materialize "$generated_css" "$app_dir/src/brand.generated.css" "$app/src/brand.generated.css"

    # Mirror shared/brand/static/** into the app's static root, preserving the
    # subdirectory layout so favicons land at / and artwork lands at /brand/.
    while IFS= read -r -d '' src; do
        rel="${src#"$owner/static/"}"
        materialize "$src" "$app_dir/static/$rel" "$app/static/$rel"
    done < <(find "$owner/static" -type f -print0)
done

if [[ "$mode" == "check" ]]; then
    if [[ "$drift" -ne 0 ]]; then
        echo "Brand sync check failed. Run scripts/sync-brand.sh to regenerate." >&2
        exit 1
    fi
    echo "Brand sync check passed."
fi
