// crates/conary-core/src/packages/deb/dpkg_lifecycle/dpkg/action.rs

//! Named actions and accepted spellings in the dpkg 1.23.7 grammar.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum DpkgNamedAction {
    Install,
    Unpack,
    RecordAvailable,
    Configure,
    Remove,
    Purge,
    ProcessTriggers,
    Verify,
    ListFiles,
    Status,
    GetSelections,
    SetSelections,
    ClearSelections,
    PrintAvailable,
    UpdateAvailable,
    MergeAvailable,
    ClearAvailable,
    ForgetOldUnavailable,
    Audit,
    YetToUnpack,
    List,
    Search,
    AddArchitecture,
    RemoveArchitecture,
    PrintArchitecture,
    PrintForeignArchitectures,
    PredependencyPackage,
    CompareVersions,
    Help,
    Version,
    Build,
    Contents,
    Control,
    Info,
    Field,
    Extract,
    VerboseExtract,
    ControlTar,
    FilesystemTar,
}

impl DpkgNamedAction {
    pub(super) const fn as_str(self) -> &'static str {
        match self {
            Self::Install => "install",
            Self::Unpack => "unpack",
            Self::RecordAvailable => "record-avail",
            Self::Configure => "configure",
            Self::Remove => "remove",
            Self::Purge => "purge",
            Self::ProcessTriggers => "triggers-only",
            Self::Verify => "verify",
            Self::ListFiles => "listfiles",
            Self::Status => "status",
            Self::GetSelections => "get-selections",
            Self::SetSelections => "set-selections",
            Self::ClearSelections => "clear-selections",
            Self::PrintAvailable => "print-avail",
            Self::UpdateAvailable => "update-avail",
            Self::MergeAvailable => "merge-avail",
            Self::ClearAvailable => "clear-avail",
            Self::ForgetOldUnavailable => "forget-old-unavail",
            Self::Audit => "audit",
            Self::YetToUnpack => "yet-to-unpack",
            Self::List => "list",
            Self::Search => "search",
            Self::AddArchitecture => "add-architecture",
            Self::RemoveArchitecture => "remove-architecture",
            Self::PrintArchitecture => "print-architecture",
            Self::PrintForeignArchitectures => "print-foreign-architectures",
            Self::PredependencyPackage => "predep-package",
            Self::CompareVersions => "compare-versions",
            Self::Help => "help",
            Self::Version => "version",
            Self::Build => "build",
            Self::Contents => "contents",
            Self::Control => "control",
            Self::Info => "info",
            Self::Field => "field",
            Self::Extract => "extract",
            Self::VerboseExtract => "vextract",
            Self::ControlTar => "ctrl-tarfile",
            Self::FilesystemTar => "fsys-tarfile",
        }
    }

    pub(super) fn parse(argument: &[u8]) -> Option<Self> {
        Some(match argument {
            b"-i" | b"--install" => Self::Install,
            b"--unpack" => Self::Unpack,
            b"-A" | b"--record-avail" => Self::RecordAvailable,
            b"--configure" => Self::Configure,
            b"-r" | b"--remove" => Self::Remove,
            b"-P" | b"--purge" => Self::Purge,
            b"--triggers-only" => Self::ProcessTriggers,
            b"-V" | b"--verify" => Self::Verify,
            b"-L" | b"--listfiles" => Self::ListFiles,
            b"-s" | b"--status" => Self::Status,
            b"--get-selections" => Self::GetSelections,
            b"--set-selections" => Self::SetSelections,
            b"--clear-selections" => Self::ClearSelections,
            b"-p" | b"--print-avail" => Self::PrintAvailable,
            b"--update-avail" => Self::UpdateAvailable,
            b"--merge-avail" => Self::MergeAvailable,
            b"--clear-avail" => Self::ClearAvailable,
            b"--forget-old-unavail" => Self::ForgetOldUnavailable,
            b"-C" | b"--audit" => Self::Audit,
            b"--yet-to-unpack" => Self::YetToUnpack,
            b"-l" | b"--list" => Self::List,
            b"-S" | b"--search" => Self::Search,
            b"--add-architecture" => Self::AddArchitecture,
            b"--remove-architecture" => Self::RemoveArchitecture,
            b"--print-architecture" => Self::PrintArchitecture,
            b"--print-foreign-architectures" => Self::PrintForeignArchitectures,
            b"--predep-package" => Self::PredependencyPackage,
            b"--compare-versions" => Self::CompareVersions,
            b"-?" | b"--help" => Self::Help,
            b"--version" => Self::Version,
            b"-b" | b"--build" => Self::Build,
            b"-c" | b"--contents" => Self::Contents,
            b"-e" | b"--control" => Self::Control,
            b"-I" | b"--info" => Self::Info,
            b"-f" | b"--field" => Self::Field,
            b"-x" | b"--extract" => Self::Extract,
            b"-X" | b"--vextract" => Self::VerboseExtract,
            b"--ctrl-tarfile" => Self::ControlTar,
            b"--fsys-tarfile" => Self::FilesystemTar,
            _ => return None,
        })
    }
}
